blank_issues_enabled: true
contact_links:
  - name: 💬 Ask on Discord
    url: https://discord.gg/GT9Q2Yz4VS
    about: Join our Discord server for bug reports, questions, support requests, or just to chat.
