export const impersonatingEmails = [
    "emailthing",
    "risky",
    "admin",
    "support",
    "helpdesk",
    "info",
    "contact",
    "billing",
    "sales",
    "service",
    "security",
    "noreply",
    "notifications",
    "manager",
    "ceo",
    "cto",
    "cfo",
    // "hr",
    "legal",
    "webmaster",
    "no-reply",
    // "customer.service",
    "feedback",
    "inquiries",
    "accounts",
    "finance",
    "marketing",
    "president",
    "board",
    "administrator",
    "system",
    "mail",
    "postmaster",
    "root",
    "register",
    "reception",
    "team",
    "office",
    "hostmaster",
    // "it",
    // "itsupport",
    "netadmin",
    "network",
    "server",
    "sysadmin",
    "technical",
    // "techsupport",
    "user",
    // "username",
    // "useradmin",
    "operations",
    // "officeadmin",
    "director",
    // "services",
    // "customercare",
    "contactus",
    "questions",
    "queries",
    "info-request",
    "data",
    // "dataprotection",
    "terms",
    "privacy",
    // "privacymatters",
    // "privacypolicy",
    // "legalteam",
    "compliance",
    "corporate",
    "exec",
    "executive",
    "founder",
    "owner",
    "principal",
    "staff",
    // "teamlead",
    // "teamleader",
    // "teammanager",
    "supervisor",
    "coordinator",
    // "mediacontact",
    "press",
    // "pressrelease",
    "media",
    // "mediainquiries",
    "official",
    "spokesperson",
    "communication",
    // "communications",
    "management",
    "strategy",
    "strategic",
    "keyaccount",
    "customerrelations",
    "clients",
    "publicrelations",
    "upgrade",
    "subscription",
    "care",
    "paid",
    "donotreply",
    "sponsor",
    "moderator",
    "admin"
];